from reflector_problem.methods.golds import design_reflector_golds
from reflector_problem.methods.gradient_descent import design_reflector_gd
from reflector_problem.methods.lbfgs import design_reflector_lbfgs